### ISSUE TITLE
Contacts getRecentlyModified not working 404

### ISSUE THREAD

**Issue by mritzco** [HubSpotWebTeam/hs-node-api#77] opened 2020-01-07 11:20 UTC
I'm trying to get a list of recently modified contacts and it keeps failing with status 404.
Similar code with companies work well.

Code Sample:
```js
const HubSpotClient = require("hubspot-api");
const client = new HubSpotClient({
  hapikey: "xxxx"
});

client.contacts
  .getRecentlyModified({ count: 5 })
  .then(response => console.log(response))
  .catch(e => console.log(e));
```

I checked the end point and it works well. I tried inspecting node execution and it seems like extra parameters are attached to the call. This is the URL i get right before the error:

URL from code Nodejs inspector:
```
https://api.hubapi.com/contacts/v1/lists/recently_updated/contacts/recent?propertyMode=value_only&formSubmissionMode=none&hapikey=HAPIKEYGOESHERE&count=5
```

If I use the same URL with CURL it fails with this error:
```
{"status":"error","message":"Any of the listed authentication credentials are missing","correlationId":"9265f45a-ded3-4a1e-b7f4-781e6d79352a","engagement":{"hapikey":"hapikey not engaged. hapikey is not present in query params.","vendorkey-gae":"vendorkey-gae not engaged. Vendorkey not found in request headers.","oauth-token":"oauth-token not engaged. OAuth access token not found in request header.","shhkey-v1":"shhkey-v1 not engaged. Shhkey not found in the request header.","internal-cookie":"internal-cookie not engaged. Cookie not found in the request.","app-cookie":"app-cookie not engaged. App cookie is not present on the request."},"requestId":"fe3ca2ec-cad0-4a11-a2f7-a19769c0578e"}
```

Once i remove this 2 arguments from the URL it works well:
```
propertyMode=value_only&formSubmissionMode=none
```

Is there a way to fix this? or am I doing something wrong.

**Comment by smcelhinney** [comment] 2020-01-07 11:34
Well spotted @mritzco - I believe the issue is here:

https://github.com/HubSpotWebTeam/hs-node-api/blob/master/src/entities/contacts.js#L182

The line needs to be changed to 
```
const mergedProps = Object.assign({}, _baseOptions, options);
```
(i.e. remove the `defaults` property. 

If you'd like to open a PR for it, I'd be happy to review and merge.

**Comment by mritzco** [comment] 2020-01-07 12:03
I'm on Bangkok time, I can't do the pull request till tomorrow. 
Whatever is the easier/better for you guys I'll be happy to follow through.

**Comment by mritzco** [comment] 2020-01-08 05:12
Pull request sent @smcelhinney thanks for your help.

**Comment by smcelhinney** [comment] 2020-02-17 19:09
Hey @mritzco - I believe this issue is now resolved, closing!

**Closed by smcelhinney** 2020-02-17 19:09 UTC
